#!/bin/bash
rm .bash_profile
cd archscripts
echo -ne "Enter your username: "
read username
useradd -m $username
pacman-key --init
pacman -Sy
pacman -S sudo
usermod -aG wheel $username
sed -i "s/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g" /etc/sudoers
echo -e "Set a password for $username"
passwd $username
cd ..
mv archscripts /home/$username
chown -R $username:$username /home/$username
su - $username -c "/home/$username/archscripts/postuser"
